### ISSUE TITLE
Activity name in metadata

### ISSUE THREAD

**Issue by MaRaSu** [pdhoopr/gps-to-gpx#13]
ActivityName from options is now used only in Track-level name-field and in the top level metadata name-field is always "Activity". However it appears that at least some Garmin devices use top level metadata in the UI and therefore always present GPX-tracks generated by this library with name "Activity".

I know very little of GPX-format however took a quick look at some other GPX-tracks e.g. those produced by Strava Routes, all those seemed to have same name-field both at the top level and track. 

Propose either a new options-field is added for the top level name-field or if it's in line with GPX-format just use existing ActivityName.

**Comment by pdhoopr** [comment]
Hi, so sorry about **just** getting around to this!

Just in case you're still interested, the `activityName` is now used in the metadata as of v1.5.0 (courtesy of @r0b0t3d).

Thank you!
