### ISSUE TITLE
Convert Date to ISO 8601

### ISSUE THREAD

**Issue by fermuch** [pdhoopr/gps-to-gpx#5]
This is a minor detail, but converting Date objects to ISO 8601 would be nice.

As of now, if you pass a Date object, you end with a UNIX TIMESTAMP. You can obviously do a `.toISOString()` previous to passing the dates, but handling it automatically would be better.

**Comment by pdhoopr** [comment]
Good point, I agree. When I have some time, hopefully in the near future, I'll look at implementing this. Thanks for the feedback!

**Comment by pdhoopr** [comment]
This should be resolved in the most recent [v1.1.0 release](https://github.com/pdhoopr/gps-to-gpx/releases/tag/v1.1.0). 

Thanks again for the comment!
